### ISSUE TITLE
dkg: compilation error in processDecryptQueue - accessing private field via interface

### ISSUE THREAD

**Issue by lucas2brh** [piplabs/story#750]
## Description

`client/x/dkg/keeper/dkg_svc.go:283` accesses `k.contractClient.ethClient.BlockNumber(ctx)`, but `k.contractClient` is typed as `types.DKGContractClient` (interface). `ethClient` is a private field on `ContractClient` struct, not exposed on the interface.

```
# github.com/piplabs/story/client/x/dkg/keeper
client/x/dkg/keeper/dkg_svc.go:283:41: k.contractClient.ethClient undefined
(type "github.com/piplabs/story/client/x/dkg/types".DKGContractClient has no field or method ethClient)
```

## Root Cause

Introduced in #727. `processDecryptQueue` needs `BlockNumber()` to check decrypt request timeout, but `DKGContractClient` interface only has `Register`, `Finalize`, `SubmitEncryptedPartialDecryption`.

## Suggested Fix

Add `BlockNumber(ctx context.Context) (uint64, error)` to `DKGContractClient` interface and implement on `ContractClient`:

```go
// types/expected_keepers.go
type DKGContractClient interface {
    Register(...) (...)
    Finalize(...) (...)
    SubmitEncryptedPartialDecryption(...) (...)
    BlockNumber(ctx context.Context) (uint64, error)  // new
}

// keeper/contract_client.go
func (c *ContractClient) BlockNumber(ctx context.Context) (uint64, error) {
    return c.ethClient.BlockNumber(ctx)
}
```

## Impact

`dkg/dev` branch does not compile as of commit 35e1dc2.

**Comment by lucas2brh** [comment]
**CI Analysis**: The `verify` check on #727 failed with "scope not set" (PR format check), not a compilation error. There is no `go build` or `go vet` step in the CI pipeline for `dkg/dev` branch. The compilation error was not caught because CI doesn't compile the code.

Suggesting adding a build check to the CI pipeline for `dkg/dev`.
