### PR TITLE
fix(dkg): expose blocknumber via contract client interface

### PR DESCRIPTION
**Pull request by lucas2brh**
## Summary

Add BlockNumber method to DKGContractClient and EthClient interfaces so processDecryptQueue can query block height without accessing private ethClient field. Fixes compilation error introduced in #727.

- Add `BlockNumber(ctx)` to `DKGContractClient` and `EthClient` interfaces
- Implement on `ContractClient`, delegates to `ethClient.BlockNumber`
- Fix caller in `dkg_svc.go` to use interface method

issue: #750

### CODE REVIEW

**Review by 0xHansLee — APPROVED** [review]

**Comment by 0xHansLee** [comment]
Please fix the failed gha (verifypr) before merging it.

**Review by jdubpark — APPROVED** [review]

**Review by jdubpark — APPROVED** [review]
